Pojedynczy film 2
annlisie/movie-me pull request #8
Opened 2017-10-29 14:04 UTC by emmaluciano

2017-10-29 17:57 UTC, p-kwiatkowski requested changes

2017-10-29 17:57 UTC, p-kwiatkowski commented on src/app/movie/shared/movie.service.ts
> +      return this.http.get('https://localhost:8443/movies/' + id)
Zamiast https://localhost:8443 wstaw environment.apiEndpoint
Przyklad: https://github.com/annlisie/movie-me/blob/master/src/app/movie/shared/movie.service.ts

2017-10-30 09:47 UTC, emmaluciano commented
Wyczyściłam ten branch, żeby w review było jak najmniej zmian.

2017-10-31 07:51 UTC, p-kwiatkowski approved these changes

2017-10-31 17:38 UTC, merged