Ocena flmow
annlisie/movie-me pull request #9
Opened 2017-11-06 20:44 UTC by emmaluciano

2017-11-11 19:01 UTC, p-kwiatkowski requested changes

2017-11-11 19:01 UTC, p-kwiatkowski commented on src/app/movie/shared/movie.service.ts.orig
> +<<<<<<< HEAD
Nierozwiązany konflikt

2017-11-11 19:01 UTC, p-kwiatkowski commented on src/app/movie/shared/movie.service.ts.orig
> +<<<<<<< HEAD
Konflikt

2017-11-12 08:51 UTC, emmaluciano commented on src/app/movie/shared/movie.service.ts.orig
> +<<<<<<< HEAD
Dzięki, przeoczyłam że dorzucam plik .orig

2017-11-12 10:41 UTC, p-kwiatkowski approved these changes

2017-11-12 15:50 UTC, merged